Fcos
Jittor/JDet pull request #29
Opened 2021-11-11 07:06 UTC by li-xl

2021-11-12 07:19 UTC, cxjyxxme commented
fcos的table加到首页readme

2021-11-13 06:46 UTC, cxjyxxme commented on projects/fcos/README.md
> +# S2ANet
写错了？

2021-11-13 06:47 UTC, li-xl commented on projects/fcos/README.md
> +# S2ANet
yes....我改下

2021-11-13 07:06 UTC, cxjyxxme requested changes

2021-11-13 07:08 UTC, li-xl commented on python/jdet/models/losses/focal_loss.py
> +        loss = (1-target)*output+max_val+jt.log(jt.maximum((-max_val).exp()+(-output -max_val).exp(),1e-10))
效果好像没区别

2021-11-13 07:08 UTC, li-xl commented on python/jdet/data/image.py
> +            index = int(os.environ['BATCH_IDX'])
用来测试单张图片的

2021-11-13 07:08 UTC, li-xl commented on tools/run_net.py
> +import torch
好的

2021-11-13 07:08 UTC, li-xl commented on tools/merge_results.py
> +    # ]
好的

2021-11-13 07:14 UTC, li-xl commented on python/jdet/models/roi_heads/gliding_head.py
>          return dets, labels
换格式了，在execute换的，和这个函数没关系

2021-11-13 07:32 UTC, cxjyxxme commented on index.html?p=%2Ftest_datas.zip.1
> +      rawPath: 'https://cloud.tsinghua.edu.cn/seafhttp/files/d78af17d\u002D4e6f\u002D4f18\u002Dbf1b\u002D4b04a2003df9/test_datas.zip',
这个去掉

2021-11-13 07:35 UTC, merged